# Generated by Django 4.2.25 on 2025-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто (НП)'),
        ),
        migrations.AddField(
            model_name='order',
            name='city_ref',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref Міста (НП)'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Відділення (НП)'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_ref',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref Відділення (НП)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто (старе)'),
        ),
    ]
