# Generated by Django 4.2.26 on 2025-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('accepted', 'Прийняте'), ('shipped', 'Відправлене'), ('completed', 'Оплачено / Завершено'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус замовлення'),
        ),
    ]
