# Generated by Django 4.2.26 on 2025-11-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ttn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ТТН Нова Пошта'),
        ),
    ]
