# Generated by Django 4.2.26 on 2026-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст банера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('banner_type', models.CharField(choices=[('info', 'Information (Blue)'), ('warning', 'Warning (Yellow)'), ('danger', 'Critical (Red)'), ('success', 'Success (Green)')], default='info', max_length=20, verbose_name='Тип (Колір)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Глобальний Банер',
                'verbose_name_plural': 'Глобальні Банери',
            },
        ),
    ]
